baseurl = "https://mt1218.github.io/"
languageCode = "en-us"
theme = "hugo-theme-stack"
title = "MT12"
copyright = "MT12. Some rights reserved."

# Theme i18n support
# Available values: ar, bn, ca, de, el, en, es, fr, hu, id, it, ja, ko, nl, pt-br, th, uk, zh-cn, zh-hk, zh-tw
DefaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

[languages.en]
languageName = "English"
title = "MT12"
weight = 1

[languages.en.params.sidebar]
subtitle = "Software Engineering and Cyber Security Student"

[languages.zh-cn]
languageName = "中文"
title = "演示站点"
weight = 2

[languages.zh-cn.params.sidebar]
subtitle = "演示说明"

[languages.ar]
languageName = "عربي"
languagedirection = "rtl"
title = "موقع تجريبي"
weight = 3

[languages.ar.params.sidebar]
subtitle = "وصف تجريبي"

[pagination]
pagerSize = 3

[permalinks]
post = "/p/:slug/"
page = "/:slug/"

[params]
mainSections = [ "post" ]
featuredImageField = "image"
rssFullContent = true

  [params.footer]
  since = 2_025
  customText = ""

  [params.dateFormat]
  published = "Jan 02, 2006"
  lastUpdated = "Jan 02, 2006 15:04 MST"

  [params.sidebar]
  emoji = ""
  subtitle = ""

    [params.sidebar.avatar]
    enabled = true
    local = true
    src = "img/avatar.jpg"

  [params.article]
  math = false
  toc = true
  readingTime = true

    [params.article.license]
    enabled = true
    default = "This post is licensed under CC BY 4.0"

[[params.widgets.homepage]]
type = "search"

[[params.widgets.homepage]]
type = "archives"

  [params.widgets.homepage.params]
  limit = 5

[[params.widgets.homepage]]
type = "categories"

  [params.widgets.homepage.params]
  limit = 10

[[params.widgets.homepage]]
type = "tag-cloud"

  [params.widgets.homepage.params]
  limit = 10

[[params.widgets.page]]
type = "toc"

[params.opengraph.twitter]
site = ""
card = "summary_large_image"

[params.defaultImage.opengraph]
enabled = false
local = false
src = ""

  [params.colorScheme]
  toggle = true
  default = "auto"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true

[menu]
main = [ ]

  [[menu.social]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/MT1218"

    [menu.social.params]
    icon = "brand-github"

  [[menu.social]]
  identifier = "linkedin"
  name = "LinkedIn"
  url = "https://linkedin.com/in/manav-thobhani-352018266"

    [menu.social.params]
    icon = "brand-linkedin"

[related]
includeNewer = true
threshold = 60
toLower = false

  [[related.indices]]
  name = "tags"
  weight = 100

  [[related.indices]]
  name = "categories"
  weight = 200

[markup.goldmark.extensions.passthrough]
enable = true

  [markup.goldmark.extensions.passthrough.delimiters]
  block = [ [ "\\[", "\\]" ], [ "$$", "$$" ] ]
  inline = [ [ "\\(", "\\)" ] ]

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 6
ordered = true
startLevel = 1

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4